### ISSUE TITLE
Not just alone

### ISSUE THREAD

**Issue by BigBlueHat** [garbados/chaiseblog#3]
I love the idea of a private journal/blog, but there may be a way to put this out in public without needing to also create Yet-Another-Comment-System and without using something like Facebook or Disq.us.

Meet, WebMention:
http://webmention.org/

It's like Pingback. Just, RESTful. :grin:

**Comment by garbados** [comment]
Closing this issue because it's a diary and it'll always be a diary.

**Comment by BigBlueHat** [comment]
Works for me. Ideally, WebMention could be done generically anyhow--and then we could all benefit!--ideally... :smiley_cat:
